### PR TITLE
RepoMenu

### PR DESCRIPTION
**Pull request by CreativeCodeCat**
Added RepoMenu #HopeItWorks

### CODE REVIEW

**Comment by XDream8** [comment]
Nice it should work with [xorg repo](https://github.com/ehawkvu/kiss-xorg)

**Comment by CreativeCodeCat** [comment]
hey mate you might like this script it will write the readme for you its still a WIP but its a start
[UpdateReadme.py](https://github.com/The-Repo-Club/kiss_repo/blob/main/updatereadme.py)

**Comment by XDream8** [comment]
Nice script

**Comment by CreativeCodeCat** [comment]
ya it works nicely to have the readme regen every time i do a push

**Pull request merged**
